/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectWindow.java
 *
 * Created on 2011-okt-08, 00:01:56
 */
package GUIComponents;

import Connection.ConnPoint;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonas
 */
public class ConnectWindow extends javax.swing.JFrame {
    MainWindow _main;
    
    Configuration.modes mode;
    /** Creates new form ConnectWindow */
    public ConnectWindow(MainWindow ancestor) {
        initComponents();
        _main = ancestor;
        _main.setTab(1);
        _main.flashStatus("Opening ConnectWindow");
        buttonGroup1.add(client);
        buttonGroup1.add(server);
        client.setSelected(true);
        mode = mode.Client;
        Configuration.centerWindow(this);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        connButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        client = new javax.swing.JRadioButton();
        server = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        hostlabel = new javax.swing.JLabel();
        remotehost = new javax.swing.JTextField();
        remoteportlabel = new javax.swing.JLabel();
        remoteport = new javax.swing.JTextField();
        hostAliasLabel = new javax.swing.JLabel();
        hostAlias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connect to -");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingOperation(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 19;
        jPanel3.add(cancelButton, gridBagConstraints);

        connButton.setText("Add User");
        connButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(connButton, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        client.setText("Client");
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });
        jPanel4.add(client);

        server.setText("Server");
        server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverActionPerformed(evt);
            }
        });
        jPanel4.add(server);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        hostlabel.setText("Host  / IP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(hostlabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(remotehost, gridBagConstraints);

        remoteportlabel.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(remoteportlabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(remoteport, gridBagConstraints);

        hostAliasLabel.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(hostAliasLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(hostAlias, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closingOperation(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closingOperation
        _main.refreshList();
    }//GEN-LAST:event_closingOperation

    private void connButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connButtonActionPerformed
        
        try {
            Configuration conf = _main.getConfiguration();
            if(conf.getConnPoint(hostAlias.getText()) instanceof ConnPoint){
                JOptionPane.showMessageDialog(this, "User Name taken: " + hostAlias.getText(), ":(", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(mode == mode.Client){
                System.out.println("Adding client " + hostAlias.getText());
                conf.addClient(InetAddress.getByName(remotehost.getText()), Integer.parseInt(remoteport.getText()), hostAlias.getText());
            } else {
                conf.addServer(hostAlias.getText(), Integer.parseInt(remoteport.getText()));
            }
            conf.getLastPoint().addDataWatcher(_main);
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Port Number?? " + remotehost.getText(), ":(", JOptionPane.WARNING_MESSAGE);
        } catch (UnknownHostException uhe) {
            JOptionPane.showMessageDialog(this, "Unknown host: " + remotehost.getText(), ":(", JOptionPane.WARNING_MESSAGE);
        }
        _main.flashStatus("Added User");
        _main.refreshList();
    }//GEN-LAST:event_connButtonActionPerformed

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
        mode = mode.Client;
        remotehost.setEnabled(true);
    }//GEN-LAST:event_clientActionPerformed

    private void serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverActionPerformed
        mode = mode.Server;
        remotehost.setEnabled(false);
    }//GEN-LAST:event_serverActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        _main.flashStatus("Cancelled Add");        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton client;
    private javax.swing.JButton connButton;
    private javax.swing.JTextField hostAlias;
    private javax.swing.JLabel hostAliasLabel;
    private javax.swing.JLabel hostlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField remotehost;
    private javax.swing.JTextField remoteport;
    private javax.swing.JLabel remoteportlabel;
    private javax.swing.JRadioButton server;
    // End of variables declaration//GEN-END:variables

}
